services:
  caddy:
    container_name: caddy-gateway
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - cart-demo

  nats:
    image: nats:latest
    container_name: nats_server
    env_file:
      - .env
    ports:
      - '4222:4222' # Client connections
      - '8222:8222' # Monitoring UI
      - '6222:6222' # Cluster communication
    # -js flag for enables JetStream (NATS persistence & streaming).
    command: ['-DV', '-m', '8222', '--auth', '${NATS_TOKEN}']
    networks: ['cart-demo']

volumes:
  caddy_data:
  caddy_config:

networks:
  cart-demo:
    name: cart-demo
    driver: bridge
